#!/usr/bin/env python3

import sys
import argparse
from git_helpers import parse_remote_url

parser = argparse.ArgumentParser()
parser.add_argument("type", nargs="?", default="repo", choices=["repo", "new-pr"])
parser.add_argument("--remote")
parser.add_argument("--branch")
args = parser.parse_args()

if args.remote is None or len(args.remote) <= 0:
    sys.exit("must specify a remote URL")

repo = parse_remote_url(args.remote)

if args.type == "home" or args.type == "repo":
    url = repo.home_url
elif args.type == "new-pr":
    url = repo.new_pr(args.branch)
    if url is None:
        sys.exit("unknown hosting service: " + repo.service)
else:
    sys.exit("unknown URL type: " + args.type)

sys.stdout.write(url + "\n")
