#!/usr/bin/env python3

import sys
import argparse
from git_helpers import get_base_url

parser = argparse.ArgumentParser()
parser.add_argument("type", nargs="?", default="repo", choices=["repo", "new-pr"])
parser.add_argument("--remote")
parser.add_argument("--branch")
args = parser.parse_args()

if args.remote is None or len(args.remote) <= 0:
    sys.exit("must specify a remote URL")

base_url, service = get_base_url(args.remote)

if args.type == "repo":
    url = base_url
elif args.type == "new-pr":
    if service == "github":
        url = base_url + f"/pull/new/{args.branch}"
    elif service == "bitbucket":
        url = base_url + f"/pull-requests/new?source={args.branch}"
    else:
        sys.exit("unknown hosting service: " + service)
else:
    sys.exit("unknown URL type: " + args.type)

sys.stdout.write(url + "\n")
